name: PR Title Validation
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci @actions/core @actions/github 

      - name: Lint PR
        run: npx tsx ./.github/scripts/pr-title.ts
        with:
          github_token: ${{ github.token }}